from __future__ import annotations

import os
import tempfile
import tomllib
from pathlib import Path

from config.settings import BASE_DIR

RUNTIME_FILE = BASE_DIR / "config" / "runtime.toml"


def load_runtime() -> dict:
    if not RUNTIME_FILE.is_file():
        return {}
    try:
        return tomllib.loads(RUNTIME_FILE.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, tomllib.TOMLDecodeError) as exc:
        raise RuntimeError(f"Invalid runtime provider configuration: {RUNTIME_FILE}") from exc


def save_runtime(
    *,
    provider: str,
    source: str,
    target: str,
    profile: str = "",
    rclone_remote: str = "",
    archive: str = "",
) -> None:
    lines = [
        "# Generated by the provider setup. Do not commit this file.",
        "[active]",
        f'provider = "{_toml_string(provider)}"',
        f'profile = "{_toml_string(profile)}"',
        f'source = "{_toml_string(source)}"',
        f'target = "{_toml_string(target)}"',
        f'archive = "{_toml_string(archive)}"',
        f'rclone_remote = "{_toml_string(rclone_remote)}"',
        "",
    ]
    RUNTIME_FILE.parent.mkdir(parents=True, exist_ok=True)
    fd, temp_name = tempfile.mkstemp(prefix="runtime-", suffix=".tmp", dir=RUNTIME_FILE.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write("\n".join(lines))
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temp_name, RUNTIME_FILE)
    finally:
        Path(temp_name).unlink(missing_ok=True)


def clear_runtime() -> None:
    RUNTIME_FILE.unlink(missing_ok=True)


def _toml_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')
