[app]
version = "1.8.3"
provider = "local"
source = "local://storage/input"
target = "local://storage/output"
source_lang = "es"
target_lang = "en"
log_level = "INFO"

[local]
retain_sources = true
input_min_age_seconds = 60

[google_drive]
source_folder_id = ""
target_folder_id = ""
archive_folder_id = ""
original_transcript_subdir = "original_transcriptions"

[rclone]
binary_file = "tools/rclone/rclone"
config_file = "secrets/rclone/rclone.conf"
remote = "remote_drive"

[providers]
